package fr.siamois.domain.models.actionunit.form;

import fr.siamois.ui.form.dto.ColumnWidth;
import fr.siamois.ui.form.dto.CustomColUiDto;
import fr.siamois.ui.form.dto.CustomFormPanelUiDto;
import fr.siamois.ui.form.dto.CustomRowUiDto;
import fr.siamois.ui.form.dto.FormUiDto;

public class ActionUnitDetailsForm extends ActionUnitForm {

    private ActionUnitDetailsForm() {
        throw new UnsupportedOperationException();
    }

    public static FormUiDto build() {
        return new FormUiDto.Builder()
                .addPanel(
                        new CustomFormPanelUiDto.Builder()
                                .name(GENERAL_LABEL_CODE)
                                .isSystemPanel(true)
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(NAME_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(true)
                                                        .width(ColumnWidth.STANDARD)
                                                        .hidden(true)
                                                        .field(IDENTIFIER_FIELD)
                                                        .isRequired(true)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(ACTION_UNIT_TYPE_FIELD)
                                                        .build())

                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(BEGIN_DATE_FIELD)
                                                        .isRequired(false)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(END_DATE_FIELD)
                                                        .isRequired(false)
                                                        .build())
                                                .build()
                                ).build()
                )
                .addPanel(
                        new CustomFormPanelUiDto.Builder()
                                .name("common.label.localisation")
                                .isSystemPanel(true)
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(MAIN_LOCATION_FIELD)
                                                        .build())
                                                .build()
                                )

                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.FULL)
                                                        .field(SPATIAL_CONTEXT_FIELD)
                                                        .build())
                                                .build()
                                ).build()
                )
                .addPanel(
                        new CustomFormPanelUiDto.Builder()
                                .name("actionunit.header.administrative")
                                .isSystemPanel(true)
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(OA_CODE_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(STATUS_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(FIELD_STATUS_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(SCIENTIFIC_MANAGER_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(HOST_STRUCTURE_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(DEVELOPER_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(PRESCRIPTION_ORDER_NUMBER_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(PRESCRIPTION_ORDER_DATE_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(PRESCRIBED_AREA_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(DESIGNATION_ORDER_NUMBER_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(DESIGNATION_ORDER_DATE_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(DEVELOPMENT_NATURE_FIELD)
                                                        .build())
                                                .build()
                                )
                                .build()
                )
                .addPanel(
                        new CustomFormPanelUiDto.Builder()
                                .name("actionunit.header.documentation")
                                .isSystemPanel(true)
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(SYSTEM_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(ZMIN_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(ZMAX_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(EXCAVATED_AREA_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(ACCESSIBLE_AREA_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(OPENING_RATE_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.FULL)
                                                        .field(PERIODS_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.FULL)
                                                        .field(SUBJECTS_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(VOLUME_COUNT_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(PAGE_COUNT_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(FIGURE_COUNT_FIELD)
                                                        .build())
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.STANDARD)
                                                        .field(APPENDIX_COUNT_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.FULL)
                                                        .field(SCIENTIFIC_NOTICE_FIELD)
                                                        .build())
                                                .build()
                                )
                                .addRow(
                                        new CustomRowUiDto.Builder()
                                                .addColumn(new CustomColUiDto.Builder()
                                                        .readOnly(false)
                                                        .width(ColumnWidth.FULL)
                                                        .field(COMMENTS_FIELD)
                                                        .build())
                                                .build()
                                )
                                .build()
                )
                .build();
    }

}
