package fr.siamois.domain.models.phase.form;

import fr.siamois.ui.form.dto.ColumnWidth;
import fr.siamois.ui.form.dto.CustomColUiDto;
import fr.siamois.ui.form.dto.CustomFormPanelUiDto;
import fr.siamois.ui.form.dto.CustomRowUiDto;
import fr.siamois.ui.form.dto.FormUiDto;

public class PhaseDetailsForm extends PhaseForm {

    public static FormUiDto build() {
        return new FormUiDto.Builder()
                .addPanel(
                        new CustomFormPanelUiDto.Builder()
                                .name("common.header.general")
                                .isSystemPanel(true)
                                .addRow(new CustomRowUiDto.Builder()
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(true)
                                                .width(ColumnWidth.STANDARD).hidden(true)
                                                .field(identifierField)
                                                .build())
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(false)
                                                .width(ColumnWidth.STANDARD)
                                                .field(typeField)
                                                .build())
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(false)
                                                .width(ColumnWidth.STANDARD)
                                                .field(titleField)
                                                .build())
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(true)
                                                .width(ColumnWidth.STANDARD).hidden(true)
                                                .field(actionUnitField)
                                                .build())
                                        .build())
                                .addRow(new CustomRowUiDto.Builder()
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(false)
                                                .width(ColumnWidth.STANDARD)
                                                .field(orderNumberField)
                                                .build())
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(false)
                                                .width(ColumnWidth.STANDARD)
                                                .field(keywordsField)
                                                .build())
                                        .build())
                                .addRow(new CustomRowUiDto.Builder()
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(false)
                                                .width(ColumnWidth.FULL)
                                                .field(descriptionField)
                                                .build())
                                        .build())
                                .build()
                )
                .addPanel(
                        new CustomFormPanelUiDto.Builder()
                                .name("common.header.chronologie")
                                .isSystemPanel(true)
                                .addRow(new CustomRowUiDto.Builder()
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(false)
                                                .width(ColumnWidth.STANDARD)
                                                .field(periodsField)
                                                .build())
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(false)
                                                .width(ColumnWidth.STANDARD)
                                                .field(lowerBoundField)
                                                .build())
                                        .addColumn(new CustomColUiDto.Builder()
                                                .readOnly(false)
                                                .width(ColumnWidth.STANDARD)
                                                .field(upperBoundField)
                                                .build())
                                        .build())
                                .build()
                )
                .build();
    }
}
