#######################
# Server Configuration
#######################
server:
  port: 8099
  forward-headers-strategy: native
  servlet:
    context-path: /siamois
    session:
      timeout: 125m
  error:
    path: /errorPages/error500.xhtml
    whitelabel:
      enabled: false

siamois:
  lang:
    default: en
    available: en, fr
  admin:
    username: ${SIAMOIS_ADMIN_LOGIN}
    password: ${SIAMOIS_ADMIN_PASSWORD}
    email: ${SIAMOIS_ADMIN_EMAIL}
  documents:
    folder-path: ${SIAMOIS_DOCUMENTS_PATH}
    allowed-types: image/jpeg, image/png, image/svg+xml, image/tiff, image/webp, image/apng, application/pdf


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
 #   platform: postgres
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 1
      idle-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false

  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog.xml

  messages:
    basename: language/messages
    encoding: UTF-8
    fallback-to-system-locale: false

  web:
    resources:
      static-locations: classpath:/static/

  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 300MB

joinfaces:
  faces:
    project-stage: production
  primefaces:
    theme: overcast

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
