#######################
# Server Configuration
#######################
server:
  port: 8099
  forward-headers-strategy: native
  servlet:
    context-path: /siamois
    session:
      timeout: 125m
  error:
    path: /errorPages/error500.xhtml
    whitelabel:
      enabled: false

siamois:
  lang:
    default: en

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
 #   platform: postgres
    url: jdbc:postgresql://localhost:5432/siamois
    username: siamois
    hikari:
      maximum-pool-size: 1000
      minimum-idle: 1
      idle-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
    change-log: classpath:/changelog/db.changelog.xml

  messages:
    basename: language/messages
    encoding: UTF-8

  web:
    resources:
      static-locations: classpath:/static/

  mvc:
    static-path-pattern: /static/**

joinfaces:
  faces:
    project-stage: production
  primefaces:
    theme: overcast

logging:
  level:
    root: INFO
    org:
      springframework:
        transaction: DEBUG
        orm.jpa: DEBUG
      hibernate:
        SQL: DEBUG
        type: DEBUG

