version: '3.8'

services:
  db:
    image: postgis/postgis
    networks:
      - siamois-net

  siamois:
    build:
      context: ../
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8099:8099"
    environment:
      CONTEXT_PATH: /
      JAVA_TOOL_OPTIONS: -Xmx4g
    networks:
      - siamois-net
    deploy:
      resources:
        limits:
          cpus: '0.5'    
          memory: 5G

networks:
  siamois-net:
